### ISSUE TITLE
creación y verificación de cuentas

### ISSUE THREAD

**Issue by Imsanty23** [ISCOUTB/DG-Work-Solution#3]

**Comment by JNicanor** [comment]
![Image](https://github.com/user-attachments/assets/8f6430d2-488c-43a8-bbce-00e3fb056de5)
![Image](https://github.com/user-attachments/assets/04a76025-857b-4e1c-a09a-ad7fb5390332)

**Comment by jairoserrano** [comment]
es con flutter...

**Comment by JNicanor** [comment]
actualizado. (El codigo está en el repositorio)
![Image](https://github.com/user-attachments/assets/e399bef9-4de6-415d-b36b-4e0605f7d06f)
![Image](https://github.com/user-attachments/assets/5b9838dc-f4c4-4cba-b437-af190adf6af8)
![Image](https://github.com/user-attachments/assets/8c1c10e2-a560-4509-9ede-1e562cde788f)
![Image](https://github.com/user-attachments/assets/f4b4da24-2636-4526-8359-6b441c7de13b)
![Image](https://github.com/user-attachments/assets/09bff731-f10c-42fd-94ad-a0b77e29446d)
![Image](https://github.com/user-attachments/assets/19cf52ad-44f7-4c0b-b58e-9313fa4f2b70)
