### ISSUE TITLE
WireFrames

### ISSUE THREAD

**Issue by Imsanty23** [ISCOUTB/DG-Work-Solution#4]

**Comment by Imsanty23** [comment]
![Image](https://github.com/user-attachments/assets/daee3f16-56de-4496-85c4-4f390426137f)
![Image](https://github.com/user-attachments/assets/0c4d1d04-8ecb-4f56-873d-f6b095fd8ebb)
![Image](https://github.com/user-attachments/assets/92f0e167-f0e9-4699-82d8-6f07636c92b9)
![Image](https://github.com/user-attachments/assets/bdf0e36d-3e79-4f02-b184-8a5a3079a997)

**Comment by HasmetG** [comment]
![Image](https://github.com/user-attachments/assets/e2ad82dc-1fcb-4668-a73d-7efd4cac87dd)
![Image](https://github.com/user-attachments/assets/ae664dc4-67c3-40d7-b8b6-796dd83a7f03)
![Image](https://github.com/user-attachments/assets/7f75788f-9aec-4e96-b03e-3fd8d0c44f6c)
![Image](https://github.com/user-attachments/assets/daacc7f4-f09a-4283-9b98-76c0dbc34663)

**Comment by jairoserrano** [comment]
adelante
