### ISSUE TITLE
Implementar la funcionalidad de subida de archivos

### ISSUE THREAD

**Issue by Imsanty23** [ISCOUTB/DG-Work-Solution#5]

**Comment by juanGonza19** [comment]
![Image](https://github.com/user-attachments/assets/c9733536-d90b-49c3-8b9c-b12f4b1c4995)![Image](https://github.com/user-attachments/assets/3b4c7d1a-709b-47c2-b2ea-6fa6c1c224f5)![Image](https://github.com/user-attachments/assets/1ae23928-6038-47d3-bff9-cc2c0f49c10c)![Image](https://github.com/user-attachments/assets/0b7b447a-840a-42f8-9a4f-730d42a60302)

**Comment by Imsanty23** [comment]
![Image](https://github.com/user-attachments/assets/f1794007-5b2e-4cc6-9399-4fea52d5b333)
![Image](https://github.com/user-attachments/assets/0ca5e8f1-c6f4-4b17-97d7-a85a487406d3)

**Comment by juanGonza19** [comment]
parte del codigo ahora en flutter
![Image](https://github.com/user-attachments/assets/c139ebaa-14f7-487f-8ac5-5647cf9d75e2)
![Image](https://github.com/user-attachments/assets/8ca03454-2868-47bb-8fa1-b72a3c14d491)
![Image](https://github.com/user-attachments/assets/9fea6b47-8f65-493a-97a5-ac818908a571)

**Comment by jairoserrano** [comment]
adelante
